# Generated by Django 5.1.1 on 2024-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='message',
            new_name='phone_name',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone',
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(default='Açıklama mevcut değil.'),
        ),
        migrations.AddField(
            model_name='phone',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(default='phone_images/default_image.jpg', upload_to='phone_images/'),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
