# Generated by Django 5.1.1 on 2024-09-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
