# Generated by Django 5.1.1 on 2024-09-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0006_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(default='computer_images/default_image.jpg', upload_to='computer_images/'),
        ),
    ]
