# Generated by Django 5.1.1 on 2024-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0007_alter_computer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earphones_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(default='earphones_images/default_image.jpg', upload_to='earphones_images/')),
                ('description', models.TextField(default='Açıklama mevcut değil.')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(default='tablet_images/default_image.jpg', upload_to='tablet_images/')),
                ('description', models.TextField(default='Açıklama mevcut değil.')),
            ],
        ),
    ]
